// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD79_pSkJivYSzFf2jID69ezOh6MQVx4Ok',
    appId: '1:1016358109064:web:7ce36b3682404758a3043d',
    messagingSenderId: '1016358109064',
    projectId: 'medvent-4b331',
    authDomain: 'medvent-4b331.firebaseapp.com',
    databaseURL:
        'https://medvent-4b331-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'medvent-4b331.appspot.com',
    measurementId: 'G-K03QR8SZPH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4OH86Xq0FH2szZ8qnQRNr2OHP7x1MLDI',
    appId: '1:1016358109064:android:b6feb54d8f532b14a3043d',
    messagingSenderId: '1016358109064',
    projectId: 'medvent-4b331',
    databaseURL:
        'https://medvent-4b331-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'medvent-4b331.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO_84NjXK-Nytysk-voha__JhBkY-n3lE',
    appId: '1:1016358109064:ios:88db67e079c59b23a3043d',
    messagingSenderId: '1016358109064',
    projectId: 'medvent-4b331',
    databaseURL:
        'https://medvent-4b331-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'medvent-4b331.appspot.com',
    iosClientId:
        '1016358109064-1690l6vbfjsairo88mpoujfbaulv89s2.apps.googleusercontent.com',
    iosBundleId: 'com.example.medvend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCO_84NjXK-Nytysk-voha__JhBkY-n3lE',
    appId: '1:1016358109064:ios:88db67e079c59b23a3043d',
    messagingSenderId: '1016358109064',
    projectId: 'medvent-4b331',
    databaseURL:
        'https://medvent-4b331-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'medvent-4b331.appspot.com',
    iosClientId:
        '1016358109064-1690l6vbfjsairo88mpoujfbaulv89s2.apps.googleusercontent.com',
    iosBundleId: 'com.example.medvend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD79_pSkJivYSzFf2jID69ezOh6MQVx4Ok',
    appId: '1:1016358109064:web:2baf93fe0ebd0f06a3043d',
    messagingSenderId: '1016358109064',
    projectId: 'medvent-4b331',
    authDomain: 'medvent-4b331.firebaseapp.com',
    databaseURL:
        'https://medvent-4b331-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'medvent-4b331.appspot.com',
    measurementId: 'G-72PR746LZ7',
  );
}
