name: medvend
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  agora_rtc_engine: ^6.3.2
  cloud_firestore: ^5.4.3
  firebase_core: ^3.6.0
  firebase_database: ^11.1.4
  flutter:
    sdk: flutter
  logger: ^2.4.0
  stacked: ^3.4.0
  stacked_firebase_auth: ^2.20.1
  stacked_services: ^1.5.1
  videosdk: 1.1.8

dev_dependencies:
  build_runner: ^2.4.5
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.1
  stacked_generator: ^1.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/
